apiVersion: apps/v1
kind: Deployment

metadata:
  name: notification
  labels:
    app: notification

spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: mnkordjani99/notification:latest
          envFrom:
            - configMapRef:
                name: notification-configmap
            - secretRef:
                name: notification-secret